name: fit
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  firebase_auth: ^4.4.0
  email_validator: ^2.1.16
  rive: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
